name: Bug Report
description: Report a bug or issue with the Compose Multiplatform Wizard plugin
labels: ["bug"]
assignees: ["heisiar"]

body:
  - type: input
    id: environment
    attributes:
      label: Plugin Version and IDE
      description: E.g., Compose Multiplatform Wizard 0.1.0 | Android Studio 2025.2.3
      placeholder: "Compose Multiplatform Wizard 0.1.0 | Android Studio 2025.2.3"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the issue
      value: |
        **Description:**
        <!-- Please describe the issue you encountered -->

        **Steps to Reproduce:**
        1. 
        2. 
        3. 

        **Expected Result:**
        <!-- What did you expect to happen? -->

        **Actual Result:**
        <!-- What actually happened? -->

        **Screenshots / Screencast:**
        <!-- Drag and drop screenshots or screencast here -->
    validations:
      required: true

